name: CI/CD pipeline

on:
  push:
    branches:
      - chore/CI-CD-v2
    tags:
      - 'v*.*.*'

env:
  JAVA_VERSION: 22
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensures previous commit is available for git show

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Set repository variables
        run: |
          echo "REPO_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "REPO_NAME_SHORT=$(echo '${{ github.event.repository.name }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Extract Project Version
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "PROJECT_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "TAG_VERSION=v$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Get current pom version
        id: current-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "CUR_VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Get previous pom version
        id: previous-version
        run: |
          PREV_VERSION=$(git show HEAD^:pom.xml | xmllint --xpath 'string(/project/version)' - 2>/dev/null || echo "unknown")
          echo "PREV_VERSION=$PREV_VERSION" >> $GITHUB_OUTPUT
          echo "Previous version: $PREV_VERSION"

      - name: Check if version changed
        id: version-check
        run: |
          CUR_VERSION="${{ steps.current-version.outputs.CUR_VERSION }}"
          PREV_VERSION="${{ steps.previous-version.outputs.PREV_VERSION }}"
          if [ -z "$CUR_VERSION" ] || [ -z "$PREV_VERSION" ] || [ "$CUR_VERSION" = "unknown" ] || [ "$PREV_VERSION" = "unknown" ]; then
            echo "Version check inconclusive (current: $CUR_VERSION, previous: $PREV_VERSION), defaulting to false"
            echo "VERSION_CHANGED=false" >> $GITHUB_OUTPUT
          elif [ "$CUR_VERSION" != "$PREV_VERSION" ]; then
            echo "Version changed from $PREV_VERSION to $CUR_VERSION"
            echo "VERSION_CHANGED=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged: $CUR_VERSION"
            echo "VERSION_CHANGED=false" >> $GITHUB_OUTPUT
          fi

      - name: Debug Versions
        run: |
          echo "Current Version: ${{ steps.current-version.outputs.CUR_VERSION }}"
          echo "Previous Version: ${{ steps.previous-version.outputs.PREV_VERSION }}"
          echo "Version Changed: ${{ steps.version-check.outputs.VERSION_CHANGED }}"

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Find JAR file
        id: find_jar
        run: |
          JAR_PATH=$(find target -name "*.jar" -not -name "*-original.jar" | head -n 1)
          if [ -z "$JAR_PATH" ]; then
            echo "Error: No JAR file found in target directory"
            exit 1
          fi
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_OUTPUT
          echo "Found JAR: $JAR_PATH"

      - name: Create GitHub Release
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.TAG_VERSION }}
          name: Release ${{ steps.get_version.outputs.PROJECT_VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: ${{ steps.find_jar.outputs.JAR_PATH }}

      - name: Set up Docker Buildx
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker metadata
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME_SHORT }}
          tags: |
            type=raw,value=${{ steps.get_version.outputs.PROJECT_VERSION }}
            type=sha

      - name: Build and push Docker image
        if: steps.version-check.outputs.VERSION_CHANGED == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME_SHORT }}:${{ steps.get_version.outputs.PROJECT_VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME_SHORT }}:latest